version: '2'
services:

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  ports:
   - 5671:5671
   - 1883:1883
  environment:
   - RABBITMQ_NODENAME=rabbitmq@rabbitmq
  volumes:
   - rabbitmq:/var/lib/rabbitmq/mnesia

 influxdb:
  image: influxdb:latest
  volumes:
   - influxdb:/var/lib/influxdb
   - ./conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  ports:
    - "8084:8083"
    - "8086:8086"
    - "8088:8088"

 telegraf:
  image: telegraf:latest
  links:
    - influxdb
  volumes:
    - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

 grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  links:
    - influxdb
  volumes:
    - grafana:/var/lib/grafana

volumes:
 influxdb:
 grafana:
 rabbitmq:
